### ISSUE TITLE
collapseStringsAfterLength not working

### ISSUE THREAD

**Issue by wasimsandhu** [TexteaInc/json-viewer#542]
Hi! I'm trying to use `collapseStringsAfterLength` but it doesn't seem to work. Here it is set to `10` for example:

<img width="1182" alt="Screenshot 2024-11-28 at 11 13 55 AM" src="https://github.com/user-attachments/assets/da620e80-bdd6-4a83-ab34-66f7e35472a7">

Here are the props I'm using:

```jsx
<JsonViewer
  className="marimo-json-output"
  rootName={name}
  theme={theme}
  value={data}
  style={{
    backgroundColor: "transparent",
  }}
  valueTypes={VALUE_TYPE}
  groupArraysAfterLength={1_000_000}
  collapseStringsAfterLength={500}
  enableClipboard={false}
/>
```

Custom css, in case it matters:

```css
.marimo-json-output {
  padding-top: 2px;
  padding-bottom: 2px;
  /* content-visibility is set by material UI;
   * when set on an element that has overflow auto, causes abrupt jumps when
   * scrolling in Chrome */
  content-visibility: unset;
  /* Coarse hack to stop children from overflowing; doesn't seem to affect
   * margin collapse. */
  overflow: auto;
  @apply text-xs;
}

.marimo-json-output span {
  text-wrap: wrap;
  word-break: break-word;
}
```
